name: Feature
description: Ajouter une nouvelle fonctionalité.
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Description complète de la fonctionnalité
  - type: textarea
    id: steps
    attributes:
      label: Étapes
      value: |
        - [ ] step name
        - [ ] step name
        ...
      render: markdown